apiVersion: apps/v1
kind: Deployment
metadata:
  name: praxiteles
  namespace: odysseia
  labels:
    heritage: "Helm"
    release: "praxiteles"
    chart: "praxiteles"
    env: k3d
    variant: k3d
    app: praxiteles
    domain: "backend"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "praxiteles"
  template:
    metadata:
      labels:
        app: "praxiteles"
        release: praxiteles
        version:
    spec:
      containers:
        - name: "praxiteles"
          image: ghcr.io/odysseia-greek/praxiteles:v0.1.0

          imagePullPolicy: Always
          env:
            - name: ENV
              value: production
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: 16Mi
              cpu: 50m
            limits:
              memory: 32Mi
