apiVersion: apps/v1
kind: Deployment
metadata:
  name: praxiteles
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "praxiteles"
  template:
    metadata:
      labels:
        app: "praxiteles"
        release: praxiteles
        version:
    spec:
      containers:
        - name: "praxiteles"
          image: ghcr.io/odysseia-greek/praxiteles:v0.1.0
          imagePullPolicy: Always
          env:
            - name: ENV
              value: production
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: 16Mi
              cpu: 50m
            limits:
              memory: 32Mi
