apiVersion: apps/v1
kind: Deployment
metadata:
  name: perdikkas
  labels:
    app: perdikkas
  annotations:
    volumes.odysseia.io/secrets: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: perdikkas
  template:
    metadata:
      labels:
        app: perdikkas
        release: perdikkas
        version: v0.0.4
      annotations:
        odysseia-greek/role: api
        odysseia-greek/access: dictionary
        perikles/accesses: "solon"
    spec:
      containers:
        - name: "perdikkas"
          image: ghcr.io/odysseia-greek/perdikkas:v0.0.4
          imagePullPolicy: Always
          env:
            - name: ELASTIC_ACCESS
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['odysseia-greek/access']
          envFrom: []
          ports:
            - containerPort: 50060
      volumes: []
