apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/makedonia
  - alexandros
  - antigonos
  - eukleides
  - demokritos
  - ptolemaios
  - hefaistion
  - legacy

labels:
  - pairs:
      environment: "k3d"
      variant: "k3d"
      domain: "backend"
    includeSelectors: false
    includeTemplates: true