apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspasia
  labels:
    app: aspasia
  annotations:
    volumes.odysseia.io/elastic-only: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspasia
  template:
    metadata:
      labels:
        app: aspasia
        release: aspasia
        version: v0.0.3
      annotations:
        perikles/accesses: "herodotos;antigonos"
        perikles/hostname: "aspasia"
        perikles/validity: "10"
    spec:
      containers:
        - name: "aspasia"
          image: ghcr.io/odysseia-greek/aspasia:v0.0.3
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: aspasia
          ports:
            - containerPort: 50060