apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apologia

resources:
  - deployment.yaml
  - ../../../../base/apologia/aspasia

components:
  - ../../../../../pyr/koinos/deployment/aristophanes
  - ../stoicheia/version/aspasia
  - ../stoicheia/images

  - ../../../../../pyr/koinos/services/grpc
  - ../../../../../pyr/koinos/resources/local/low
  - ../../../../../pyr/koinos/common-env/base/deploy
  - ../../../../../pyr/koinos/downwardapi/version/deploy

patches:
  - target:
      version: v1
      kind: Service
    patch: |-
      - op: replace
        path: /metadata/name
        value: aspasia
      - op: replace
        path: /spec/selector/app
        value: aspasia
