apiVersion: v1
kind: ConfigMap
metadata:
  name: kritias
data:
  VERSION: "v0.1.0"
  ALEXANDROS_SERVICE: "http://alexandros.makedonia.svc:5000"
  HERODOTOS_SERVICE: "http://herodotos.olympia.svc:5000"
