apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
  - target:
      kind: Node
      name: pella-hellenistike
    path: pella.yaml
  - target:
      kind: Node
      name: alexandreia-hellenistike
    path: alexandreia.yaml
