apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agora
resources:
  - ../../../base/eupalinos
  - statefulset.yaml

components:
  - ../../../../pyr/koinos/services/queue

patches:
  - target:
      version: v1
      kind: Service
    patch: |-
      - op: replace
        path: /metadata/name
        value: eupalinos
      - op: replace
        path: /spec/selector/app
        value: eupalinos
