apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/eupalinos
  - ../../../../pyr/koinos/services/queue
  - statefulset.yaml

patches:
  - target:
      version: v1
      kind: Service
    patch: |-
      - op: replace
        path: /metadata/name
        value: eupalinos
      - op: replace
        path: /spec/selector/app
        value: eupalinos
