apiVersion: builtin
kind: PatchTransformer
metadata:
  name: add-common-env-to-deployments
patch: |
  - op: add
    path: /spec/template/spec/containers/0/envFrom/-
    value:
      configMapRef:
        name: odysseia-common-env
target:
  kind: Deployment
  name: ".*"
