apiVersion: apps/v1
kind: Deployment
metadata:
  name: antigonos
  labels:
    app: antigonos
  annotations:
    mount.odysseia.io/combined: "true"
    volumes.odysseia.io/combined: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: antigonos
  template:
    metadata:
      labels:
        app: antigonos
        release: antigonos
        version: v0.1.0
      annotations:
        odysseia-greek/role: api
        odysseia-greek/access: dictionary
        perikles/accesses: "solon"
        perikles/hostname: "antigonos"
        perikles/validity: "10"
    spec:
      containers:
        - name: "antigonos"
          image: ghcr.io/odysseia-greek/antigonos:dev
          imagePullPolicy: Always
          env:
            - name: ELASTIC_ACCESS
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['odysseia-greek/access']
          envFrom:
            - configMapRef:
                name: antigonos
          volumeMounts:
            - name: antigonos-certs
              mountPath: /app/config/antigonos
              readOnly: true
          ports:
            - containerPort: 50060
      volumes:
        - name: antigonos-certs
          secret:
            secretName: antigonos-tls-certs