apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apologia
resources:
  - deployment.yaml
  - scaler.yaml
  - ../../../../base/apologia/sokrates

components:
  - ../../../../../pyr/koinos/deployment/aristophanes
  - ../../../../../pyr/koinos/deployment/sophokles
  - ../../../../../pyr/koinos/deployment/serviceaccount
  - ../../../../../pyr/koinos/services/graphql
  - ../../../../../pyr/koinos/resources/local/mid
  - ../../../../../pyr/koinos/transformers/volumes/combined
  - ../../../../../pyr/koinos/transformers/mounts/combined
  - ../../../../../pyr/koinos/common-env/base/deploy

patches:
  - target:
      version: v1
      kind: Service
    patch: |-
      - op: replace
        path: /metadata/name
        value: sokrates
      - op: replace
        path: /spec/selector/app
        value: sokrates
