---
# Source: dionysios/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: melissos
data:
  JOB_NAME: "demokritos"
  JOB_NAMESPACE: "makedonia"
  EUPALINOS_CHANNEL: "parmenides"

