apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: delphi

resources:
  - deployment.yaml
  - ../../base/perikles

components:
  - ../../../pyr/koinos/resources/local/mid
  - ../../../pyr/koinos/transformers