apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: attike
resources:
  - external-secrets.yaml
  - ns.yaml
  - metrics-rbac.yaml

components:
  - ../../../pyr/koinos/common-env/overlays/local