apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: attike
resources:
  - ../../../../base/attike/eupalinos
  - daemonset.yaml

components:
  - ../../../../../pyr/koinos/resources/local/low