apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: attike
resources:
  - ../../../../base/attike/eupalinos
  - statefulset.yaml

components:
  - ../../../../../pyr/koinos/services/grpc

patches:
  - target:
      version: v1
      kind: Service
    patch: |-
      - op: replace
        path: /metadata/name
        value: eupalinos
      - op: replace
        path: /spec/selector/app
        value: eupalinos-attike
  - target:
      version: v1
      kind: ConfigMap
      name: eupalinos-attike
    patch: |-
      - op: replace
        path: /data/ENV
        value: "local"