apiVersion: apps/v1
kind: Deployment
metadata:
  name: pheidias
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "pheidias"
  template:
    metadata:
      labels:
        app: "pheidias"
        release: pheidias
        version: v0.2.2
    spec:
      containers:
        - name: "pheidias"
          image: ghcr.io/odysseia-greek/pheidias:v0.2.2
          imagePullPolicy: Always
          env:
            - name: NODE_ENV
              value: production
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: 16Mi
              cpu: 50m
            limits:
              memory: 32Mi
