apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: olympia
resources:
  - deployment.yaml
  - scaler.yaml
  - tracemap.yaml
  - ir.yaml
  - ../../../../base/olympia/homeros

components:
  - ../../../../../pyr/koinos/deployment/aristophanes
  - ../../../../../pyr/koinos/deployment/sophokles
  - ../../../../../pyr/koinos/deployment/serviceaccount
  - ../../../../../pyr/koinos/services/graphql
  - ../../../../../pyr/koinos/resources/local/mid
  - ../../../../../pyr/koinos/transformers/volumes
  - ../../../../../pyr/koinos/transformers/mounts
  - ../../../../../pyr/koinos/common-env/base/deploy

patches:
  - target:
      version: v1
      kind: Service
    patch: |-
      - op: replace
        path: /metadata/name
        value: homeros
      - op: replace
        path: /spec/selector/app
        value: homeros
