apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/olympia
  - homeros
  - herodotos
  - pheidias
  - melissos
  - protagoras

labels:
  - pairs:
      environment: "local"
      variant: "k0s"
      domain: "backend"
    includeSelectors: false
    includeTemplates: true