apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: alexandreia

resources:
  - deployment.yaml
  - job.yaml
  - scaler.yaml
  - ../../../../base/alexandreia/dionysios

components:
  - ../../../../../pyr/koinos/deployment/aristophanes
  - ../../../../../pyr/koinos/deployment/periandros
  - ../../../../../pyr/koinos/deployment/aristides
  - ../../../../../pyr/koinos/services/http
  - ../../../../../pyr/koinos/resources/local/high
  - ../../../../../pyr/koinos/resources/local/job
  - ../../../../../pyr/koinos/transformers/volumes/secrets
  - ../../../../../pyr/koinos/common-env/base/deploy
  - ../../../../../pyr/koinos/common-env/base/job
  - ../../../../../pyr/koinos/downwardapi/version/deploy

patches:
  - target:
      version: v1
      kind: Service
    patch: |-
      - op: replace
        path: /metadata/name
        value: dionysios
      - op: replace
        path: /spec/selector/app
        value: dionysios
