apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: makedonia
resources:
  - job.yaml

components:
  - ../../../../../pyr/koinos/deployment/aristides
  - ../../../../../pyr/koinos/resources/local/job
  - ../../../../../pyr/koinos/transformers/volumes/combined
  - ../../../../../pyr/koinos/transformers/mounts/combined
  - ../../../../../pyr/koinos/common-env/base/job
