apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: delphi

resources:
  - deployment.yaml
  - ../../base/solon

components:
  - ../../../pyr/koinos/deployment/aristophanes
  - ../../../pyr/koinos/deployment/peisistratos
  - ../../../pyr/koinos/deployment/sophokles
  - ../../../pyr/koinos/resources/local/mid
  - ../../../pyr/koinos/transformers