apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: olympia

resources:
  - deployment.yaml
  - job.yaml
  - scaler.yaml

components:
  - ../../../../../pyr/koinos/deployment/aristophanes
  - ../../../../../pyr/koinos/deployment/periandros
  - ../../../../../pyr/koinos/deployment/sophokles
  - ../../../../../pyr/koinos/deployment/aristides
  - ../../../../../pyr/koinos/deployment/serviceaccount
  - ../../../../../pyr/koinos/services/http
  - ../../../../../pyr/koinos/resources/local/low
  - ../../../../../pyr/koinos/resources/local/job
  - ../../../../../pyr/koinos/transformers/volumes/existing
  - ../../../../../pyr/koinos/transformers/mounts/existing
  - ../../../../../pyr/koinos/common-env/base/deploy
  - ../../../../../pyr/koinos/common-env/base/job

patches:
  - target:
      version: v1
      kind: Service
    patch: |-
      - op: replace
        path: /metadata/name
        value: herodotos
      - op: replace
        path: /spec/selector/app
        value: herodotos
