apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/makedonia
  - alexandros
  - antigonos
  - eukleides
  - demokritos
  - ptolemaios
  - hefaistion
  - parmenion
  - perdikkas
  - dareios

labels:
  - pairs:
      environment: "romaioi"
      variant: "k0s"
      domain: "backend"
    includeSelectors: false
    includeTemplates: true