apiVersion: apps/v1
kind: Deployment
metadata:
  name: alkibiades
  labels:
    app: alkibiades
  annotations:
    volumes.odysseia.io/existing: "true"
    mounts.odysseia.io/existing: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alkibiades
  template:
    metadata:
      labels:
        app: alkibiades
        release: alkibiades
        version: v0.1.1
      annotations:
        odysseia-greek/role: api
        odysseia-greek/access: journey-quiz
        perikles/accesses: "solon"
        perikles/hostname: "alkibiades"
        perikles/validity: "10"
    spec:
      containers:
        - name: "alkibiades"
          image: ghcr.io/odysseia-greek/alkibiades:v0.1.1

          imagePullPolicy: Always
          env:
            - name: ELASTIC_ACCESS
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['odysseia-greek/access']
          envFrom:
            - configMapRef:
                name: alkibiades
          volumeMounts:
            - name: alkibiades-certs
              mountPath: /app/config/alkibiades
              readOnly: true
          ports:
            - containerPort: 50060
      volumes:
        - name: alkibiades-certs
          secret:
            secretName: alkibiades-tls-certs