apiVersion: apps/v1
kind: Deployment
metadata:
  name: aiskhylos
  labels:
    app: aiskhylos
  annotations:
    volumes.odysseia.io/secrets: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aiskhylos
  template:
    metadata:
      labels:
        app: aiskhylos
        release: aiskhylos
        version: v0.2.2
      annotations:
        odysseia-greek/role: creator
        odysseia-greek/access: tracing;metrics;metrics_rollup
        perikles/accesses: solon
    spec:
      containers:
        - name: "aiskhylos"
          image: ghcr.io/odysseia-greek/aiskhylos:v0.2.2
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: aiskhylos
          env:
            - name: ELASTIC_ACCESS
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['odysseia-greek/access']
      volumes: []
