apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: attike
resources:
  - deployment.yaml
  - job.yaml
  - ../../../../base/attike/aiskhylos

components:
  - ../../../../../pyr/koinos/resources/local/mid
  - ../../../../../pyr/koinos/deployment/periandros
  - ../../../../../pyr/koinos/deployment/aristides
  - ../../../../../pyr/koinos/resources/local/job
  - ../../../../../pyr/koinos/transformers/volumes/secrets
  - ../../../../../pyr/koinos/common-env/base/job
  - ../../../../../pyr/koinos/common-env/base/deploy