apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: attike
resources:
  - deployment.yaml
  - ../../../../base/attike/aiskhylos

components:
  - ../../../../../pyr/koinos/resources/local/low
  - ../../../../../pyr/koinos/transformers/volumes
  - ../../../../../pyr/koinos/common-env/base/init
  - ../../../../../pyr/koinos/common-env/base/deploy
  - ../../../../../pyr/koinos/resources/local/job
  - ../../../../../pyr/koinos/common-env/base/job
