apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: makedonia

resources:
  - deployment.yaml
  - ../../../../base/makedonia/ptolemaios

components:
  - ../../../../../pyr/koinos/deployment/aristophanes
  - ../../../../../pyr/koinos/services/grpc
  - ../../../../../pyr/koinos/resources/local/low
  - ../../../../../pyr/koinos/transformers/volumes/elastic
  - ../../../../../pyr/koinos/common-env/base/deploy
  - ../../../../../pyr/koinos/downwardapi/version/deploy

patches:
  - target:
      version: v1
      kind: Service
    patch: |-
      - op: replace
        path: /metadata/name
        value: ptolemaios
      - op: replace
        path: /spec/selector/app
        value: ptolemaios
