apiVersion: apps/v1
kind: Deployment
metadata:
  name: antigonos
  labels:
    app: antigonos
  annotations:
    volumes.odysseia.io/secrets: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: antigonos
  template:
    metadata:
      labels:
        app: antigonos
        release: antigonos
        version: v0.0.3
      annotations:
        odysseia-greek/role: api
        odysseia-greek/access: dictionary
        perikles/accesses: "solon"
        perikles/hostname: "antigonos"
        perikles/validity: "10"
    spec:
      containers:
        - name: "antigonos"
          image: ghcr.io/odysseia-greek/antigonos:v0.0.3
          imagePullPolicy: Always
          env:
            - name: ELASTIC_ACCESS
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['odysseia-greek/access']
          envFrom: []
          volumeMounts:
            - name: antigonos-certs
              mountPath: /app/config/antigonos
              readOnly: true
          ports:
            - containerPort: 50060
      volumes:
        - name: antigonos-certs
          secret:
            secretName: antigonos-tls-certs