apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: olympia

resources:
  - cronjob.yaml
  - job.yaml
  - ../../../../base/olympia/melissos

components:
  - ../../../../../pyr/koinos/resources/local/low
  - ../../../../../pyr/koinos/common-env/base/cronjob
  - ../../../../../pyr/koinos/common-env/base/job
  - ../../../../../pyr/koinos/deployment/aristophanes
  - ../../../../../pyr/koinos/deployment/periandros
  - ../../../../../pyr/koinos/deployment/sophokles
  - ../../../../../pyr/koinos/deployment/aristides
  - ../../../../../pyr/koinos/cronjob/aristides
  - ../../../../../pyr/koinos/cronjob/aristophanes
  - ../../../../../pyr/koinos/cronjob/periandros
  - ../../../../../pyr/koinos/cronjob/sophokles