apiVersion: apps/v1
kind: Deployment
metadata:
  name: aristippos
  labels:
    app: aristippos
  annotations:
    mount.odysseia.io/combined: "true"
    volumes.odysseia.io/combined: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aristippos
  template:
    metadata:
      labels:
        app: aristippos
        release: aristippos
        version: v0.1.0
      annotations:
        odysseia-greek/role: api
        odysseia-greek/access: media-quiz
        perikles/accesses: "alexandros;solon;herodotos"
    spec:
      containers:
        - name: "aristippos"
          image: ghcr.io/odysseia-greek/aristippos:v0.1.0

          imagePullPolicy: Always
          env:
            - name: ELASTIC_ACCESS
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['odysseia-greek/access']
          envFrom:
            - configMapRef:
                name: aristippos
          ports:
            - containerPort: 50060
