all:
  children:
    poleis-acc:
      children:
        poleis-acc-controller:
          hosts:
            pella:
              ansible_user: pi
              ansible_ssh_private_key_file: ~/.ssh/id_raspie
              ansible_host: 192.168.1.191
              arch: rpi5
        poleis-acc-workers:
          hosts:
            antioch:
              ansible_user: pi
              ansible_ssh_private_key_file: ~/.ssh/id_raspie
              ansible_host: 192.168.1.124
              arch: rpi4
