apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apologia

resources:
  - deployment.yaml
  - job.yaml
  - ../../../../base/apologia/xenofon

components:
  - ../../../../../pyr/koinos/deployment/aristophanes
  - ../../../../../pyr/koinos/deployment/periandros
  - ../../../../../pyr/koinos/deployment/aristides
  - ../../../../../pyr/koinos/services/grpc
  - ../../../../../pyr/koinos/resources/local/mid
  - ../../../../../pyr/koinos/resources/local/job
  - ../../../../../pyr/koinos/transformers/volumes/secrets
  - ../../../../../pyr/koinos/common-env/base/deploy
  - ../../../../../pyr/koinos/common-env/base/job
  - ../../../../../pyr/koinos/downwardapi/version/deploy
  - ../stoicheia/version/xenofon
  - ../stoicheia/images

patches:
  - target:
      version: v1
      kind: Service
    patch: |-
      - op: replace
        path: /metadata/name
        value: xenofon
      - op: replace
        path: /spec/selector/app
        value: xenofon
