apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - ns.yaml
  - repo.yaml
  - release.yaml
configMapGenerator:
  - name: kps-values
    files: [values.yaml]
generatorOptions:
  disableNameSuffixHash: true
