apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/apologia
  - sokrates
  - alkibiades
  - antisthenes
  - aristippos
  - kritias
  - kriton
  - xenofon
  - meletos
  - aspasia

components:
  - stoicheia/images
  - stoicheia/version

labels:
  - pairs:
      environment: "romaioi"
      variant: "k0s"
      domain: "backend"
    includeSelectors: false
    includeTemplates: true
