apiVersion: apps/v1
kind: Deployment
metadata:
  name: alexander
  labels:
    app: alexander
  annotations:
    mount.odysseia.io/combined: "true"
    volumes.odysseia.io/combined: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alexandros
  template:
    metadata:
      labels:
        app: alexandros
        release: alexandros
        version: v0.3.0
      annotations:
        perikles/accesses: "antigonos"
        perikles/hostname: "alexandros"
        perikles/validity: "10"
    spec:
      containers:
        - name: alexander
          image: ghcr.io/odysseia-greek/alexandros:v0.3.0
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: alexandros
          ports:
            - name: graphql
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 20
