apiVersion: apps/v1
kind: Deployment
metadata:
  name: herodotos
  labels:
    app: herodotos
  annotations:
    volumes.odysseia.io/combined: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: herodotos
  template:
    metadata:
      labels:
        app: herodotos
        release: herodotos
        version: v0.2.0
      annotations:
        odysseia-greek/role: api
        odysseia-greek/access: text
        perikles/accesses: "solon;aristarchos"
        perikles/hostname: "herodotos"
        perikles/validity: "10"
    spec:
      containers:
        - name: "herodotos"
          image: ghcr.io/odysseia-greek/herodotos:v0.2.0

          imagePullPolicy: Always
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ELASTIC_ACCESS
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['odysseia-greek/access']
          envFrom:
            - configMapRef:
                name: herodotos
          volumeMounts:
            - name: herodotos-certs
              mountPath: /app/config/herodotos
              readOnly: true
            - name: aristarchos-certs
              mountPath: /app/config/aristarchos
              readOnly: true
          ports:
            - containerPort: 5000
              name: http
          livenessProbe:
            httpGet:
              path: /herodotos/v1/health
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /herodotos/v1/ping
              port: 5000
            initialDelaySeconds: 1
            periodSeconds: 20
      volumes:
        - name: herodotos-certs
          secret:
            secretName: herodotos-tls-certs
        - name: aristarchos-certs
          secret:
            secretName: aristarchos-tls-certs