apiVersion: apps/v1
kind: Deployment
metadata:
  name: alexandros
  labels:
    app: alexandros
  annotations:
    volumes.odysseia.io/existing: "true"
    mounts.odysseia.io/existing: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alexandros
  template:
    metadata:
      labels:
        app: alexandros
        release: alexandros
        version: v0.2.0
      annotations:
        odysseia-greek/role: api
        odysseia-greek/access: dictionary
        perikles/accesses: "solon;herodotos"
        perikles/hostname: "alexandros"
        perikles/validity: "10"
    spec:
      containers:
        - name: "alexandros"
          image: ghcr.io/odysseia-greek/alexandros:v0.2.0
          imagePullPolicy: Always
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ELASTIC_ACCESS
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['odysseia-greek/access']
          envFrom:
            - configMapRef:
                name: alexandros
          volumeMounts:
            - name: herodotos-certs
              mountPath: /app/config/herodotos
              readOnly: true
            - name: alexandros-certs
              mountPath: /app/config/alexandros
              readOnly: true
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /alexandros/v1/health
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /alexandros/v1/ping
              port: 5000
            initialDelaySeconds: 1
            periodSeconds: 20
      volumes:
        - name: herodotos-certs
          secret:
            secretName: herodotos-tls-certs
        - name: alexandros-certs
          secret:
            secretName: alexandros-tls-certs