apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: makedonia
resources:
  - deployment.yaml
  - scaler.yaml
  - ir.yaml
  - service.yaml
  - ../../../../base/makedonia/alexandros

components:
  - ../../../../../pyr/koinos/deployment/aristophanes
  - ../../../../../pyr/koinos/deployment/sophokles
  - ../../../../../pyr/koinos/deployment/serviceaccount
  - ../../../../../pyr/koinos/resources/local/mid
  - ../../../../../pyr/koinos/transformers/volumes/combined
  - ../../../../../pyr/koinos/transformers/mounts/combined
  - ../../../../../pyr/koinos/common-env/base/deploy
