apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: delphi

resources:
  - cronjob.yaml
  - ../../../../base/ktesias

components:
  - ../../../../../../thrasyboulos/pyr/koinos/resources/local/mid
  - ../../../../../../thrasyboulos/pyr/koinos/common-env/base/cronjob
  - ../../../../../../thrasyboulos/pyr/koinos/transformers/volumes/secrets
  - ../../../../../../thrasyboulos/pyr/koinos/cronjob/aristides
  - ../../../../../../thrasyboulos/pyr/koinos/cronjob/periandros
