---
# Source: homeros/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: homeros
data:
  ELASTIC_SEARCH_SERVICE: "http://aristoteles-es-http.agora.svc:9200"
  ENV: "k3d"
  TLS_ENABLED: "true"
  CERT_ROOT: "/app/config"
  ALEXANDROS_SERVICE: "http://alexandros:5000"
  DIONYSIOS_SERVICE: "http://dionysios:5000"
  GATHER_METRICS: "true"
  HERODOTOS_SERVICE: "http://herodotos:5000"
  SOKRATES_GRAPHQL_ADDRESS: "http://sokrates.apologia.svc:8080/sokrates/graphql"