---
# Source: homeros/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: homeros
data:
  ALEXANDROS_SERVICE: "http://alexandros:5000"
  DIONYSIOS_SERVICE: "http://dionysios:5000"
  HERODOTOS_SERVICE: "http://herodotos:5000"
  SOKRATES_GRAPHQL_ADDRESS: "http://sokrates.apologia.svc:8080/sokrates/graphql"