apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspasia
  labels:
    app: aspasia
  annotations:
    volumes.odysseia.io/existing: "true"
    mounts.odysseia.io/existing: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspasia
  template:
    metadata:
      labels:
        app: aspasia
        release: aspasia
        version: v0.0.1
      annotations:
        perikles/accesses: "herodotos;antigonos"
        perikles/hostname: "aspasia"
        perikles/validity: "10"
    spec:
      containers:
        - name: "kriton"
          image: ghcr.io/odysseia-greek/aspasia:v0.0.1
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: aspasia
          volumeMounts:
            - name: aspasia-certs
              mountPath: /app/config/aspasia
              readOnly: true
          ports:
            - containerPort: 50060
      volumes:
        - name: aspasia-certs
          secret:
            secretName: aspasia-tls-certs