apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: attike
resources:
  - job.yaml
  - deployment.yaml
  - ../../../base/attike/euripides

components:
  - ../../../../pyr/koinos/deployment/aristophanes
  - ../../../../pyr/koinos/deployment/periandros
  - ../../../../pyr/koinos/deployment/sophokles
  - ../../../../pyr/koinos/deployment/aristides
  - ../../../../pyr/koinos/resources/local/low
  - ../../../../pyr/koinos/resources/local/job
  - ../../../../pyr/koinos/transformers/volumes/combined