apiVersion: apps/v1
kind: Deployment
metadata:
  name: polykleitos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "polykleitos"
  template:
    metadata:
      labels:
        app: "polykleitos"
        release: polykleitos
        version:
    spec:
      containers:
        - name: "polykleitos"
          image: ghcr.io/odysseia-greek/polykleitos:v0.0.1
          imagePullPolicy: Always
          env:
            - name: ENV
              value: production
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: 32Mi
              cpu: 50m
            limits:
              memory: 32Mi
