apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
spec:
  interval: 10m
  targetNamespace: traefik
  install:
    createNamespace: false
    crds: Create
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
  chart:
    spec:
      chart: traefik
      version: "34.2.0"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
  values:
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    deployment:
      kind: Deployment
    # Make Traefik listen on 8080/8443
    additionalArguments:
      - "--entryPoints.web.address=:8080"
      - "--entryPoints.websecure.address=:8443"
    ports:
      web:
        port: 8080
        hostPort: 8080
      websecure:
        port: 8443
        hostPort: 8443
        tls:
          enabled: true
    service:
      enabled: true
      type: ClusterIP
    podSecurityContext:
      fsGroup: 65532