apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 10m
  targetNamespace: traefik
  install:
    createNamespace: true
    crds: Create
    remediation: { retries: -1 }
  upgrade:
    crds: CreateReplace
    remediation: { retries: -1 }
  chart:
    spec:
      chart: traefik
      version: "34.2.0"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
  values:
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet

    deployment:
      kind: Deployment

    additionalArguments:
      - "--entryPoints.web.address=:8080"
      - "--entryPoints.web.http.redirections.entrypoint.to=websecure"
      - "--entryPoints.web.http.redirections.entrypoint.scheme=https"
      - "--entryPoints.websecure.address=:8443"
      - "--api.dashboard=true"

    ports:
      web:
        port: 8080
      websecure:
        port: 8443
        tls:
          enabled: true


    service:
      enabled: true
      type: ClusterIP

    podSecurityContext:
      fsGroup: 65532