apiVersion: apps/v1
kind: Deployment
metadata:
  name: perikles
  labels:
    env: k3d
    variant: k0s
    app: perikles
    domain: "backend"
  annotations:
    volumes.odysseia.io/elastic: "true"
    mount.odysseia.io/elastic: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: perikles
  template:
    metadata:
      labels:
        app: perikles
        release: perikles
        version: v0.1.10
    spec:
      serviceAccountName: periklessa
      containers:
        - name: perikles
          image: ghcr.io/odysseia-greek/perikles:v0.1.10
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: perikles
            - configMapRef:
                name: elastic-roles-and-cnp
          env:
            - name: ENV
              value: "k3d"
            - name: PORT
              value: "4443"
            - name: TLS_FILES
              value: /app/config
            - name: CRD_NAME
              value: perikles-mapping
            - name: L7_MODE
              value: "true"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - containerPort: 4443
              name: webhook-tcp
          volumeMounts:
            - name: webhook-certs
              mountPath: /app/config
              readOnly: true
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /perikles/v1/ping
              port: 4443
            initialDelaySeconds: 20
            periodSeconds: 20
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /perikles/v1/ping
              port: 4443
            initialDelaySeconds: 1
            periodSeconds: 20
      volumes:
        - name: webhook-certs
          secret:
            secretName: perikles-certs
