apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: delphi

resources:
  - deployment.yaml
  - ../../../../base/delphi/perikles

components:
  - ../../../../../../thrasyboulos/pyr/koinos/resources/local/mid
  - ../../../../../../thrasyboulos/pyr/koinos/transformers/volumes
  - ../../../../../../thrasyboulos/pyr/koinos/transformers/mounts