apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: delphi

resources:
  - deployment.yaml
  - ../../../../base/delphi/perikles

components:
  - ../../../../../../thrasyboulos/pyr/koinos/resources/local/mid

labels:
  - pairs:
      environment: "romaioi"
      variant: "k0s"
      domain: "backend"
    includeSelectors: false
    includeTemplates: true