all:
  children:
    poleis-prd:
      hosts:
        athenai.hellas:
          ansible_user: pi
          ansible_ssh_private_key_file: ~/.ssh/id_raspie
          ansible_host: 192.168.1.121
          arch: rpi5
        sparta.hellas:
          ansible_user: pi
          ansible_ssh_private_key_file: ~/.ssh/id_raspie
          ansible_host: 192.168.1.122
          arch: rpi5
        megara.hellas:
          ansible_user: pi
          ansible_ssh_private_key_file: ~/.ssh/id_raspie
          ansible_host: 192.168.1.123
          arch: rpi5
        thebai.hellas:
          ansible_user: pi
          ansible_ssh_private_key_file: ~/.ssh/id_raspie
          ansible_host: 192.168.1.124
          arch: rpi4
        korinth.hellas:
          ansible_user: pi
          ansible_ssh_private_key_file: ~/.ssh/id_raspie
          ansible_host: 192.168.1.125
          arch: rpi4
        argos.hellas:
          ansible_user: pi
          ansible_ssh_private_key_file: ~/.ssh/id_raspie
          ansible_host: 192.168.1.126
          arch: rpi4
      children:
        servers-prd:
          hosts:
            sparta.hellas:
        workers-prd:
          hosts:
            athenai.hellas:
            thebai.hellas:
            korinth.hellas:
            argos.hellas:
            megara.hellas: