# solon-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: solon
  labels:
    env: k3d
    variant: k3d
    app: solon
    domain: "backend"
  annotations:
    volumes.odysseia.io/combined: "true"
    mount.odysseia.io/combined: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solon
  template:
    metadata:
      labels:
        app: solon
        release: solon
        version: v0.1.4
      annotations:
        elastic/indices: "dictionary;grammar;text;quiz;tracing;metrics;aggregator"
        elastic/roles: "api;seeder;hybrid;creator;alias"
        perikles/hostname: "solon"
        perikles/validity: "365"
        solon/namespaces: "attike;olympia;makedonia;apologia"
    spec:
      serviceAccountName: solon-access-sa
      initContainers:
        - name: peisistratos
          image: ghcr.io/odysseia-greek/peisistratos:v0.1.3
          imagePullPolicy: Always
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: AUTH_METHOD
              value: token
          envFrom:
            - configMapRef:
                name: solon
            - configMapRef:
                name: odysseia-common-env
          volumeMounts:
            - name: vault-server-tls
              mountPath: /app/config/vault
              readOnly: true
      containers:
        - name: "solon"
          image: ghcr.io/odysseia-greek/solon:v0.2.0
          imagePullPolicy: Always
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SOLON_MANAGED_NAMESPACES
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['solon/namespaces']
            - name: AUTH_METHOD
              value: kubernetes
            - name: ELASTIC_SEARCH_USER
              valueFrom:
                secretKeyRef:
                  key: user
                  name: solon-user
            - name: ELASTIC_SEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: solon-user
          envFrom:
            - configMapRef:
                name: solon
          ports:
            - containerPort: 5443
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /solon/v1/health
              port: 5443
            initialDelaySeconds: 20
            periodSeconds: 20
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /solon/v1/health
              port: 5443
            initialDelaySeconds: 1
            periodSeconds: 20
          resources:
            requests:
              memory: 64Mi
              cpu: 200m
            limits:
              memory: 256Mi
