apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agora
resources:
  - ns.yaml
  - cnp-solon.yaml
  - cnp-homeros.yaml
  - cnp-operator.yaml
  - cnp-sokrates.yaml
  - cnp-melissos.yaml
  - cnp-alexandros.yaml
  - cnp-ptolemaios.yaml
  - cnp-aspasia.yaml
  - theofrastos
