apiVersion: builtin
kind: PatchTransformer
metadata:
  name: add-version-label-to-deployment
patch: |
  - op: add
    path: /spec/template/spec/containers/0/env/-
    value:
      name: VERSION
      valueFrom:
        fieldRef:
          fieldPath: metadata.labels['version']
target:
  kind: Deployment
  name: ".*"
