apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: delphi
resources:
  - ../../../../base/delphi/vault
  - ir.yaml
  - certificate.yaml

patches:
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: vault
    path: patch-release.yaml