apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Environment-specific configurations
configMapGenerator:
  - name: elastic-config
    namespace: odysseia
    literals:
      - ENVIRONMENT=acc
      - MEMORY_LIMIT=2Gi
      - CPU_LIMIT=1000m

patches:
  - target:
      kind: Deployment
      name: elastic
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 2Gi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 1000m
