apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: attike
resources:
  - deployment.yaml

components:
  - ../../../../../pyr/koinos/services/frontend

patches:
  - target:
      version: v1
      kind: Service
    patch: |-
      - op: replace
        path: /metadata/name
        value: praxiteles
      - op: replace
        path: /spec/selector/app
        value: praxiteles
