apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: delphi

resources:
  - deployment.yaml
  - certificate.yaml
  - ../../../../base/delphi/solon

components:
  - ../../../../../../thrasyboulos/pyr/koinos/deployment/aristophanes
  - ../../../../../../thrasyboulos/pyr/koinos/resources/local/mid
  - ../../../../../../thrasyboulos/pyr/koinos/transformers/volumes/combined
  - ../../../../../../thrasyboulos/pyr/koinos/transformers/mounts/combined
  - ../../../../../../thrasyboulos/pyr/koinos/common-env/base/deploy