apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
      version: 34.2.0
  install:
    crds: Skip
    createNamespace: true
  interval: 10m
  targetNamespace: traefik
  values:
    additionalArguments:
    - --entryPoints.web.address=:8080
    - --entryPoints.websecure.address=:8443
    - --api.dashboard=true
    deployment:
      kind: Deployment
    dnsPolicy: ClusterFirstWithHostNet
    hostNetwork: true
    podSecurityContext:
      fsGroup: 65532
    ports:
      traefik:
        expose:
          default: false
          internal: true
        port: 9000
      web:
        nodePort: 30080
        port: 8080
      websecure:
        nodePort: 30443
        port: 8443
        tls:
          enabled: false
    service:
      enabled: true
      type: NodePort
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: dashboard
  namespace: traefik
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: PathPrefix(`/dashboard`) || PathPrefix(`/api`)
    services:
    - kind: TraefikService
      name: api@internal
