apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: delphi
resources:
  - ns.yaml
  - external-secrets.yaml
  - secrets

components:
  - ../../../pyr/koinos/common-env/overlays/local