apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: delphi
resources:
  - ns.yaml
  - external-secrets.yaml
  - secrets
  - metrics-rbac.yaml
  - cnp-herodotos.yaml
  - cnp-herakleitos.yaml
  - cnp-demokritos.yaml
  - cnp-alexandros.yaml
  - cnp-euripides.yaml
  - cnp-anaximenes.yaml

components:
  - ../../../pyr/koinos/common-env/overlays/local