apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: makedonia

resources:
  - deployment.yaml
  - cnp.yaml

patches:
  - target:
      version: v1
      kind: Service
    patch: |-
      - op: replace
        path: /metadata/name
        value: alexandros-legacy
      - op: replace
        path: /spec/selector/app
        value: alexandros-legacy
