apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: makedonia

resources:
  - deployment.yaml
  - cnp.yaml

components:
  - ../../../../../pyr/koinos/deployment/aristophanes
  - ../../../../../pyr/koinos/deployment/periandros

  - ../../../../../pyr/koinos/deployment/aristides

  - ../../../../../pyr/koinos/services/http
  - ../../../../../pyr/koinos/resources/local/high
  - ../../../../../pyr/koinos/transformers/volumes/existing
  - ../../../../../pyr/koinos/transformers/mounts/existing
  - ../../../../../pyr/koinos/transformers/volumes/combined
  - ../../../../../pyr/koinos/transformers/mounts/combined
  - ../../../../../pyr/koinos/common-env/base/deploy

patches:
  - target:
      version: v1
      kind: Service
    patch: |-
      - op: replace
        path: /metadata/name
        value: alexandros-legacy
      - op: replace
        path: /spec/selector/app
        value: alexandros-legacy
