apiVersion: apps/v1
kind: Deployment
metadata:
  name: antisthenes
  labels:
    app: antisthenes
  annotations:
    volumes.odysseia.io/secrets: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: antisthenes
  template:
    metadata:
      labels:
        app: antisthenes
        release: antisthenes
        version: v0.1.3
      annotations:
        odysseia-greek/role: api
        odysseia-greek/access: grammar-quiz
        perikles/accesses: "alexandros-legacy;solon;herodotos"
    spec:
      containers:
        - name: "antisthenes"
          image: ghcr.io/odysseia-greek/antisthenes:v0.1.3

          imagePullPolicy: Always
          env:
            - name: ELASTIC_ACCESS
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['odysseia-greek/access']
          envFrom:
            - configMapRef:
                name: antisthenes
          volumeMounts: []
          ports:
            - containerPort: 50060
      volumes: []