apiVersion: apps/v1
kind: Deployment
metadata:
  name: kriton
  labels:
    app: kriton
  annotations:
    volumes.odysseia.io/existing: "true"
    mounts.odysseia.io/existing: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kriton
  template:
    metadata:
      labels:
        app: kriton
        release: kriton
        version: v0.1.1
      annotations:
        odysseia-greek/role: api
        odysseia-greek/access: dialogue-quiz
        perikles/accesses: "solon"
        perikles/hostname: "kriton"
        perikles/validity: "10"
    spec:
      containers:
        - name: "kriton"
          image: ghcr.io/odysseia-greek/kriton:v0.1.1

          imagePullPolicy: Always
          env:
            - name: ELASTIC_ACCESS
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['odysseia-greek/access']
          envFrom:
            - configMapRef:
                name: kriton
          volumeMounts:
            - name: kriton-certs
              mountPath: /app/config/kriton
              readOnly: true
          ports:
            - containerPort: 50060
      volumes:
        - name: kriton-certs
          secret:
            secretName: kriton-tls-certs