apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/attike
  - sophokles
  - eupalinos
  - aiskhylos
  - euripides

labels:
  - pairs:
      environment: "local"
      variant: "k0s"
      domain: "tracing"
    includeSelectors: false
    includeTemplates: true