apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: olympia

resources:
  - cronjob.yaml

components:
  - ../../../../../pyr/koinos/resources/local/low
  - ../../../../../pyr/koinos/common-env/base/cronjob
