apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/apologia
  - sokrates
  - alkibiades
  - antisthenes
  - aristippos
  - kritias
  - kriton
  - xenofon

labels:
  - pairs:
      environment: "k3d"
      variant: "k3d"
      domain: "backend"
    includeSelectors: false
    includeTemplates: true