---
# Source: dionysios/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: euripides
data:
  ELASTIC_SEARCH_SERVICE: "http://aristoteles-es-http.agora.svc:9200"
  ENV: "k3d"
  TLS_ENABLED: "true"
  CERT_ROOT: "/app/config"
  MAX_AGE: "5"
  GATHER_METRICS: "true"
