---
# Source: dionysios/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: euripides
data:
  EUPALINOS_TRACING_SERVICE: "eupalinos.attike.svc.cluster.local:50060"
  TRACE_ID_CHANNEL: "euripides"
  VERSION: "0.2.0g"