# Source: dionysios/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: euripides
  namespace: odysseia
spec:
  selector:
    app: euripides
  ports:
    - name: "gateway"
      port: 8080
      targetPort: 8080