apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: delphi
resources:
  - admission-webhook.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - configmap.yaml
  - secret.yaml
  - service.yaml
  - serviceaccount.yaml
  - role.yaml
  - binding.yaml
