apiVersion: v1
kind: Service
metadata:
  name: perikles
spec:
  selector:
    app: perikles
  ports:
  - appProtocol: https
    name: https-webhook
    port: 443
    protocol: TCP
    targetPort: 4443