apiVersion: apps/v1
kind: Deployment
metadata:
  name: kritias
  labels:
    app: kritias
  annotations:
    mount.odysseia.io/combined: "true"
    volumes.odysseia.io/combined: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kritias
  template:
    metadata:
      labels:
        app: kritias
        release: kritias
        version: v0.1.0
      annotations:
        odysseia-greek/role: api
        odysseia-greek/access: multiple-choice-quiz
        perikles/accesses: "alexandros;solon;herodotos"
    spec:
      containers:
        - name: "kritias"
          image: ghcr.io/odysseia-greek/kritias:v0.1.0

          imagePullPolicy: Always
          env:
            - name: ELASTIC_ACCESS
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['odysseia-greek/access']
          envFrom:
            - configMapRef:
                name: kritias
          ports:
            - containerPort: 50060
