apiVersion: v2
appVersion: 0.0.1
description: Service to create the baseline elastic config
name: theofrastos
version: 0.0.1
home: https://www.odysseia-greek.com
sources:
  - https://github.com/odysseia-greek/agora
  - https://github.com/odysseia-greek/agora/tree/main/theofrastos
dependencies:
  - name: koinos
    version: ">= 0.1.0"
    repository: "file://../koinos"