name: theofrastos
testMode: true
namespace: odysseia
serviceAccountName: theofrastossa
configMapName: elastic-roles-and-users
services:
    job:
        limits:
            memory: 128Mi
        name: theofrastos
        requests:
            cpu: 500m
            memory: 64Mi
    tests:
        labels:
            domain: testing

images:
    imageRepo: ghcr.io/odysseia-greek/
    repo: theofrastos
    tag: v0.0.1
