apiVersion: apps/v1
kind: Deployment
metadata:
  name: theofrastos
  namespace: odysseia
  labels:
    heritage: "Helm"
    release: "theofrastos"
    chart: "theofrastos"
    env: k3d
    variant: k3d
    app: theofrastos
    domain: "backend"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: theofrastos
      release: theofrastos
  template:
    metadata:
      labels:
        app: theofrastos
        release: theofrastos
        version: v0.0.1
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
        - name: "theofrastos"
          image: ghcr.io/odysseia-greek/theofrastos:v0.0.1
          imagePullPolicy: Always
          env:
            - name: ENV
              value: "k3d"
            - name: CONFIGMAP_NAME
              value: elastic-roles-and-users
            - name: ELASTIC_SEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: aristoteles-es-elastic-user
                  key: elastic
            - name: ELASTIC_USER
              value: elastic
            - name: ELASTIC_SEARCH_SERVICE
              value: "http://aristoteles-es-http:9200"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - configMapRef:
                name: elastic-roles-and-users
          resources:
            requests:
              memory: 64Mi
              cpu: 500m
            limits:
              memory: 128Mi
      restartPolicy: Always